In [1]:
!pip install requests

Requirement already satisfied: requests in ./opt/anaconda3/lib/python3.9/site-packages (2.28.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./opt/anaconda3/lib/python3.9/site-packages (from requests) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in ./opt/anaconda3/lib/python3.9/site-packages (from requests) (3.2)
Requirement already satisfied: charset-normalizer<3,>=2 in ./opt/anaconda3/lib/python3.9/site-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in ./opt/anaconda3/lib/python3.9/site-packages (from requests) (2021.10.8)

In [2]:
import requests
import pandas as pd

In [3]:
player_info_url = 'https://stats.nba.com/stats/leaguedashplayerstats?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2022-23&SeasonSegment=&SeasonType=Playoffs&ShotClockRange=&StarterBench=&TeamID=0&VsConference=&VsDivision=&Weight='

In [4]:
headers  = {
    'Connection': 'keep-alive',
    'Accept': 'application/json, text/plain, */*',
    'x-nba-stats-token': 'true',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
    'x-nba-stats-origin': 'stats',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-Mode': 'cors',
    'Referer': 'https://stats.nba.com/',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
}

In [5]:
response = requests.get(url=player_info_url, headers=headers).json()

In [6]:
player_info = response['resultSets'][0]['rowSet']

In [10]:
nba_df = pd.DataFrame(player_info)

In [12]:
nba_df

,0,1,2,3,4,5,6,7,8,9,...,56,57,58,59,60,61,62,63,64,65
0,203932,Aaron Gordon,Aaron,1610612743,DEN,27.0,10,7,3,0.700,...,42,14,6,42,52,2,55,33,5,56
1,1628988,Aaron Holiday,Aaron,1610612737,ATL,26.0,1,1,0,1.000,...,140,130,187,178,189,147,203,56,5,192
2,201143,Al Horford,Al,1610612738,BOS,36.0,11,6,5,0.545,...,3,130,80,135,100,14,46,33,5,52
3,203458,Alex Len,Alex,1610612758,SAC,29.0,7,3,4,0.429,...,63,119,75,118,152,34,146,56,5,144
4,1629599,Amir Coffey,Amir,1610612746,LAC,25.0,1,0,1,0.000,...,140,130,187,178,189,123,208,56,5,208
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,202083,Wesley Matthews,Wesley,1610612749,MIL,36.0,2,0,2,0.000,...,51,60,120,101,112,216,113,56,5,118
212,1630214,Xavier Tillman,Xavier,1610612763,MEM,24.0,6,2,4,0.333,...,37,12,32,120,85,105,58,33,5,65
213,1629139,Yuta Watanabe,Yuta,1610612751,BKN,28.0,1,0,1,0.000,...,140,130,187,101,146,168,174,56,5,154
214,1630192,Zeke Nnaji,Zeke,1610612743,DEN,22.0,3,3,0,1.000,...,140,130,187,178,169,123,180,56,5,175
215,1630533,Ziaire Williams,Ziaire,1610612763,MEM,21.0,4,2,2,0.500,...,140,93,182,164,174,134,185,56,5,179

In [17]:
# Save as CSV
nba_df.to_csv('NAME.csv',index=False)